// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using traveltech2.Models.Data;

namespace traveltech2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210402085251_init7")]
    partial class init7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("traveltech2.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HeadID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeadID");

                    b.ToTable("App");
                });

            modelBuilder.Entity("traveltech2.Models.Head", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Head");
                });

            modelBuilder.Entity("traveltech2.Models.Links", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MenuItemsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemsId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("traveltech2.Models.MenuItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenusID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenusID");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("traveltech2.Models.Menus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HeadID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HeadID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("traveltech2.Models.App", b =>
                {
                    b.HasOne("traveltech2.Models.Head", "Head")
                        .WithMany()
                        .HasForeignKey("HeadID");
                });

            modelBuilder.Entity("traveltech2.Models.Links", b =>
                {
                    b.HasOne("traveltech2.Models.MenuItems", null)
                        .WithMany("Links")
                        .HasForeignKey("MenuItemsId");
                });

            modelBuilder.Entity("traveltech2.Models.MenuItems", b =>
                {
                    b.HasOne("traveltech2.Models.Menus", "Menus")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenusID");
                });

            modelBuilder.Entity("traveltech2.Models.Menus", b =>
                {
                    b.HasOne("traveltech2.Models.Head", "Head")
                        .WithMany("Menus")
                        .HasForeignKey("HeadID");
                });
#pragma warning restore 612, 618
        }
    }
}
